<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Page header -->
    <div class="bg-white shadow-sm">
      <div class="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between">
          <NuxtLink to="/" class="flex items-center text-gray-600 hover:text-gray-900 transition-colors">
            <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Home
          </NuxtLink>
        </div>
        <div class="mt-8 text-center">
          <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl">Terms of Service</h1>
          <p class="mt-4 text-xl text-gray-500">Please read these terms carefully before using our service.</p>
        </div>
      </div>
    </div>

    <!-- Main content -->
    <div class="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div class="bg-white shadow-lg rounded-lg p-8">
        <div class="prose prose-lg max-w-none">
          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Welcome</h2>
            <p class="text-gray-700">Welcome to South Park Character Creator service. By using our services, you agree to these terms. Please read them carefully.</p>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Service Description</h2>
            <p class="text-gray-700">We provide a South Park style character creation service that allows users to generate personalized South Park style characters through text prompts or uploaded images. The service includes the following features:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Text to Character Image: Convert text descriptions into South Park style character images</li>
              <li>Image to Character Image: Transform uploaded images into South Park style character images</li>
              <li>Character Customization: Support for adjusting character appearance, clothing, expressions, and other features</li>
              <li>Download and save generated character images</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Generated Content Usage Rules</h2>
            <p class="text-gray-700">Regarding South Park style characters generated using our service:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Personal Use: You may use generated characters for personal and non-commercial purposes free of charge</li>
              <li>Commercial Use: Commercial usage requires additional authorization or subscription to the appropriate commercial plan</li>
              <li>Attribution: Generated character images must be credited as "Generated by South Park Character Creator"</li>
              <li>Usage Restrictions: Generated characters may not be used for any illegal, inappropriate, or rights-infringing purposes</li>
              <li>Character Ownership: Users own the usage rights to generated character images, subject to these terms</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Subscriptions and Payments</h2>
            <p class="text-gray-700">We offer the following subscription plans:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Free Trial: New users receive 2 free generations upon registration</li>
              <li>Basic Plan: Includes a fixed number of character generations per month</li>
              <li>Premium Plan: Provides more generations and advanced customization features</li>
              <li>Commercial Plan: For users requiring commercial usage</li>
              <li>Subscription Renewal: Subscriptions will automatically renew unless cancelled</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Service Usage Rules</h2>
            <p class="text-gray-700">When using our service, you agree not to:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Generate or upload any illegal, harmful, threatening, abusive, harassing, defamatory, obscene, or otherwise objectionable content</li>
              <li>Infringe upon the intellectual property rights or other rights of others</li>
              <li>Circumvent our usage restrictions or access control measures</li>
              <li>Use any automated means to access the service unless specifically permitted</li>
              <li>Engage in activities that may damage the service, user experience, or infrastructure</li>
              <li>Use generated characters for commercial purposes without specific authorization</li>
              <li>Imitate or copy features of official South Park characters</li>
              <li>Use generated characters in any way that may damage the South Park brand image</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Intellectual Property</h2>
            <p class="text-gray-700">Regarding intellectual property rights involved in our service:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Service Content: Our website, services, and related technology are protected by intellectual property laws</li>
              <li>User Content: You retain all rights to your uploaded content but grant us usage rights to provide the service</li>
              <li>Generated Content: Usage rights for generated character images depend on your subscription plan</li>
              <li>South Park Brand: We are officially licensed by South Park, but users must not infringe upon South Park's intellectual property</li>
              <li>Feedback: Feedback you provide about our service may be freely used by us</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Limitation of Liability</h2>
            <p class="text-gray-700">Our services are provided "as is" without any warranties of any kind. To the maximum extent permitted by law:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>We are not responsible for service interruptions, delays, or inaccuracies</li>
              <li>We are not responsible for any consequences that may result from your use of generated characters</li>
              <li>Our liability for any damages you may suffer is limited to the amount you have paid to us</li>
              <li>We do not guarantee that generated characters will fully meet your expectations</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Service Changes and Termination</h2>
            <p class="text-gray-700">We may:</p>
            <ul class="list-disc pl-6 mt-4 space-y-2 text-gray-700">
              <li>Modify, suspend, or terminate any aspect of the service at any time</li>
              <li>Suspend or terminate your access in case of violation of these terms</li>
              <li>Notify users when significant changes to the service occur</li>
              <li>Adjust service content according to South Park official requirements</li>
            </ul>
          </section>

          <section class="mb-12">
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Terms Updates</h2>
            <p class="text-gray-700">We may update these Terms of Service from time to time. Significant changes will be communicated via email or in-service notifications. Continued use of our services after such changes indicates your acceptance of the modified terms.</p>
          </section>

          <section>
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p class="text-gray-700">If you have any questions about these Terms of Service, please contact us:</p>
            <p class="text-gray-700 mt-2">Email: support@southparkai.com</p>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useHead, useSeoMeta } from 'nuxt/app'

// @ts-ignore: Nuxt macro function
definePageMeta({
  layout: 'default',
  name: 'terms-of-service'
})

useHead({
  link: [{ rel: 'canonical', href: 'https://www.southparkai.com/subsidiary/terms-of-service' }]
})

useSeoMeta({
  title: 'South Park Character Creator | Terms of Service & Usage Rules',
  description: 'South Park Character Creator Terms: Learn about our character generation service, account usage, character generation rights, and commercial usage terms.'
})
</script> 